### ISSUE TITLE
Add a way to create roles and databases in each PG cluster using Ansible inventory

### ISSUE THREAD

**Issue by drybjed** [debops/ansible-postgresql#1]
Roles and databases in PostgreSQL clusters can be created using `postgresql_user` and `postgresql_db` Ansible modules, which is great for application roles, but not very useful if you want to have custom roles or databases on your servers (unless you write a specific playbook for that).

It would be useful if possible, to add some tasks that can create roles and databases defined in each cluster definition in inventory.

**Comment by scosist** [comment]
I started taking a stab at this but then I got lost on the expected structure of custom roles and databases for postgresql. Initially, I was modelling these after your implementation for mysql with `mysql_databases` and `mysql_users` but then I noticed where you mention here it would be useful to add tasks to create these <i>as defined</i> in each cluster definition. If I understand correctly, you are referring to `postgresql_default_cluster` and `postgresql_clusters` definitions (https://github.com/debops/ansible-postgresql/blob/master/defaults/main.yml#L105). Should I then expect to create custom roles and databases based on the following structure?
```yaml
postgresql_default_cluster:
  - name: 'main'
    port: '5432'
    hba:
      - user: 'custom_user_1'
        database: 'custom_database_1'
      - user: 'custom_user_2'
        database: 'custom_database_2'
```
In the case that custom roles and databases need to be defined by another Ansible role, rather than redefine `postgresql_default_cluster`, perhaps another name like `postgresql_default_cluster_custom` would be used. I question whether this structure is the best way to go for defining custom roles and databases. Have I understood your meaning or am I completely off base?
