### ISSUE TITLE
allow does not work

### ISSUE THREAD

**Issue by triplem** [debops/ansible-postgresql#11]
I have the following settings:

```
# Setup the default cluster.
postgresql_default_cluster:
  - name: 'main'
    port: '5432'

    listen_addresses: '0.0.0.0'
    hba:
      # Allow your master app host to communicate to this database server.
      - address: '{{ rails_deploy_hosts_master }}'
        interface: 'eth0'

    # Make sure the firewall also allows your master app host access.
    allow: '{{ rails_deploy_hosts_master }}'
```

Which is pretty much the same like written in the documentation for the rails_deploy task. As soon as I try to run my playbook, I do get the following error of ferm:

```
failed: [192.168.0.61] => {"changed": false, "cmd": ["ferm", "--slow", "/etc/ferm/ferm.conf"], "delta": "0:00:00.122701", "end": "2015-03-03 19:29:20.568813", "rc": 1, "start": "2015-03-03 19:29:20.446112", "warnings": []}
stderr: iptables v1.4.21: host/network `a' not found
Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.4.21: host/network `a' not found
Try `ip6tables -h' or 'ip6tables --help' for more information.

Firewall rules rolled back.
```

This looks like the ferm template of postgresql is slightly screwed.

**Comment by drybjed** [comment]
Variable with a list of allowed hosts/networks is well, a list. :-) Try writing it like this:
```
allow: [ '{{ rails_deploy_hosts_master }}' ]
```
I guess I will need to revisit PostgreSQL role sometime.

**Comment by triplem** [comment]
Hm, looks like the documentation of this role needs some adjustments. See  https://github.com/debops/debops/wiki/Solutions-to-problems-you-may-encounter#debopspostgresql

**Comment by drybjed** [comment]
```
allow:
      - '192.168.0.0/16'
```
This is another way to specify a list in YAML. But it could be made clearer.

**Comment by triplem** [comment]
Me seems to be stupid, but this does not work either, still the same message.

**Comment by drybjed** [comment]
Can you show contents of ferm configuration file which was generated?

**Comment by triplem** [comment]
Sure: 

```
 This file is managed by Ansible, all changes will be lost

# Default PostgreSQL allow list is empty

protocol tcp dport 5432 {
        @def $ITEMS = ( @ipfilter( (a e d i h m l o p s r t y _) ) );
        @if @ne($ITEMS,"") {
                saddr $ITEMS ACCEPT;
        }
}
```

**Comment by triplem** [comment]
When I do a debug on '{{ rails_deploy_hosts_master }}', I do get the correct IP.

**Comment by drybjed** [comment]
Did you updated `postgresql_default_cluster` variable?

**Comment by triplem** [comment]
sure: 

```
# Setup the default cluster.
postgresql_default_cluster:
  - name: 'main'
    port: '5432'

    listen_addresses: '0.0.0.0'
    hba:
      # Allow your master app host to communicate to this database server.
      - address: '{{ rails_deploy_hosts_master }}'
        interface: 'eth0'

    # Make sure the firewall also allows your master app host access.
    allow:
      - '{{ rails_deploy_hosts_master }}'
```
