### ISSUE TITLE
postgresql_user: syntax

### ISSUE THREAD

**Issue by noizo** [debops/ansible-postgresql#28]
Hi.
I was trying to create postgresql user with

```
- name: Setup BARMAN db user
  become: yes
  become_user: postgres
  postgresql_user:
    state: present
    ssl_mode: prefer
    name: "{{barman_db_user}}"
    password: "{{barman_db_password}}"
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB
```
This task can not be completed (if i will replay role, it will pass somehow)

But if i will use this syntax, everything goes fine.
```
- name: Setup BARMAN db user
  postgresql_user:
    state=present
    ssl_mode=prefer
    name={{barman_db_user}}
    password={{barman_db_password}}
    role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB
  become: yes
  become_user: postgres
```
